### ISSUE TITLE
mapbox-gl neccessary dependency?

### ISSUE THREAD

**Issue by jeroenkampinga** [SamSamskies/react-map-gl-geocoder#126]
I'm using `react-map-gl-geocoder` in combination with [react-map-gl](https://visgl.github.io/react-map-gl/). When inspecting my bundle I see `mapbox-gl.js` is bundled twice. Once from `react-map-gl` and once as (peer)dependency from `react-map-gl-geocoder`. Is there a way to remove the duplicate code when combining this package with `react-map-gl`

![bundle](https://user-images.githubusercontent.com/3184189/134679491-a3f3179f-d68f-451b-965d-3a08ebaba1a0.png)
e.

**Comment by SamSamskies** [comment]
I'm not sure, but this project is pretty much in maintenance mode, so you could just copy pasta the code into your codebase instead of installing it as a dependency. It's only one file. I've always purposely kept all the code in one file to make it easy to copy pasta. Everything you need is in this file https://github.com/SamSamskies/react-map-gl-geocoder/blob/master/src/index.js.

**Comment by SamSamskies** [comment]
I think the problem is that I forgot to add `mapbox-gl` as a peer dependency.
