### ISSUE TITLE
Set input to show only part of the result

### ISSUE THREAD

**Issue by thanhphuong612** [SamSamskies/react-map-gl-geocoder#29]
Hi, 

First, thank you for all the hard work.

Is there a way I can show only a part of the result in input field? For example, after selecting a value from the dropdown `Orlando International Airport, Orlando, Florida 32827, United States`, the input field shows only `Orlando International Airport`.

I tried to set it manually in `onResult `, but the input is back to the original value after the component reloads.

Thank you.

**Comment by SamSamskies** [comment]
Hi @thanhphuong612, sorry, there isn't a way to do that. Just curious, why do you want to truncate the option they picked?

**Comment by SamSamskies** [comment]
Also, onResult cannot be used to set the value of the input. It's used to give the parent component access to the value of the result object when selecting an option.

**Comment by thanhphuong612** [comment]
Hi @SamSamskies , thanks for getting back to me.

Just for styling purpose, I am developing a flyout that allowing users to filter the search results. The `x` and number icon are on top of the result option, which does not look good to me.

Is there a way I can work around please?

![image](https://user-images.githubusercontent.com/25516507/55487132-80f1e700-55fb-11e9-99e1-69a72c8c00c7.png)

**Comment by SamSamskies** [comment]
I'll think about adding another prop to show the result short name instead of the full text, but you may want to consider building a Geocoder component from scratch for the level of customization that you are doing. You could use the Mapbox Geocoding API to fetch the results and then build your custom component with that data. https://docs.mapbox.com/api/search/#geocoding. This would give you more control over how the component looks.

Another option would be to use CSS to make it so the text doesn't go behind the `x` and number icon.

If you need a fix ASAP, you could just copy and paste my Geocoder component into your codebase and change line 200 to `this.cachedResult = result.text`. You may also need to add `this.geocoder.setInput(this.cachedResult)` after that line. https://github.com/SamSamskies/react-map-gl-geocoder/blob/master/src/index.js#L200

**Comment by thanhphuong612** [comment]
Thanks for the suggestion, currently I do not have bandwidth to build a Geocoder component from scratch. If you could add another prop to show the result short name, that would be great. 
Personally I do not refer to copy your code and make changes from there, however, I would do that if it's my only option.

Thanks.

**Comment by SamSamskies** [comment]
Hi @thanhphuong612, I found a hack to do what you are trying to do by caching the result in the parent and using the onInit prop to set the input value. See example here: https://codesandbox.io/s/546xr6z35x. Be advised that this is not guaranteed to work in future releases though. Right now I'm creating a new Mapbox geocoder object on every render so onInit is also being called on every render. In the future, I may be smarter about it and only recreate it when necessary. 

The reason I'm hesitant about adding a displayShortName prop is that the short name of the result isn't unique. I could just make a note about that in the documentation though. I'm going to need more time to think about this.

Here's an example:
full name: San Francisco, California, United States
short name: San Francisco

full name: San Francisco, Zulia, Venezuela
short name: San Francisco

**Comment by SamSamskies** [comment]
Another option would be for me to add an inputValue prop that lets you set the value of the input to whatever you want when it renders. Let me think about it. In the meantime, feel free to use the hack I posted in the last comment.

**Comment by thanhphuong612** [comment]
Thanks for the hack. It's working perfectly for me, and I can set whatever value I want.
You are right about the `displayShortName` prop, it may confuse user. I think adding `inputValue` prop is a better option.

Again, thanks for your help and very quick response.

**Comment by SamSamskies** [comment]
No problem. Let me know if you have any other issues I can help with.
