### ISSUE TITLE
Using componentDidUpdate means that geocoder will not render on initial load

### ISSUE THREAD

**Issue by jaronheard** [SamSamskies/react-map-gl-geocoder#3]
First off, useful thing that you made. Thanks!

I'm attempting to add geocoder functionality to our map component for Civic (https://github.com/hackoregon/civic), and decided to give using your package a try. 

I was able to get it working, but the geocoder won't render on initial load until after you interact with the map.

Looking at your code, you are using componentDidUpdate to check for the presence and render the geocoder. This means that the geocoder will only appear after component updates, not on initial load. A quick fix would be to call the same code in componentDidMount.

Here's my code:
https://github.com/hackoregon/civic/pull/363/files#diff-d00726a23a264cadbb4187a041e71c16

Let me know if you have questions!

**Comment by SamSamskies** [comment]
Thanks for catching that. I didn't notice because I resize the map on page load in my example which triggers the update.

I didn't use componentDidMount because the mapRef is undefined in that context.

For now, I'll just post a quick fix by force updating in componentDidMount. When I have more free time, I'll think of a better fix and actually write some tests.
