### ISSUE TITLE
Return key blurs suggestion list on mobile

### ISSUE THREAD

**Issue by timpegas** [SamSamskies/react-map-gl-geocoder#67]
Great work with this library @SamSamskies 👍 
I have integrated `react-map-gl-geooder` in my webapp as it bundles really well with the `react-map-gl` library. I have the following issue, though:
Whlle on a mobile device, focusing the geocoder input triggers the keyboard, thus hiding half of the suggestion list results. Swiping up/down the suggestion list triggers map movement instead of hiding the keyboard in order to see the full suggestion list. 

On a first note, I created a custom map controller for pan movements on suggesstion list to stop gestures propagation to the map (#22).
Now what's left is to blur the input field every time the geocoder element (either the input or the suggestions) is panned. 

This might be a tough nut to crack so I figured maybe its easier looking at it from another perspective i.e. blur the input whenever the return key is pressed, while persisting the suggestion list.

See attachement: https://res.cloudinary.com/dwmew0qd3/video/upload/v1588703418/geocoder-suggestions-bug.mov

**Comment by SamSamskies** [comment]
Hi @timpegas. Is there a reason that you need more than 5 suggestions? By default, 5 suggestions are shown because generally that should be enough. 

If you do need to customize it further and display the suggestions even without the input focused, I think it would be better to roll your own geocoder component that is not a wrapper of `mapbox-gl-geocoder`. You can use the Mabpox geocoding API directly and borrow the concepts used in `mapbox-gl-geocoder` to build your own geocoder component.

**Comment by timpegas** [comment]
@SamSamskies I see your point, I was hoping I could achieve something more responsive, without having to limit the suggestion list results.

Arguably, implementing a custom geocoder will do the work. This was the last resort for me, seeing there is a plethora of ready packages that bundle well with mapbox, if you also include the limited amount of time for implementation atm. Anyway, thank so so much for taking the time to come back to me. I appreciate it.
