### ISSUE TITLE
Dotted line around entry box when active

### ISSUE THREAD

**Issue by kjkurtz** [SamSamskies/react-map-gl-geocoder#80]
The newest version (2.1.2) has a dotted line around the geocoder text box when it is active. This can be seen in the main codesandbox example: https://codesandbox.io/s/react-map-gl-geocoder-using-containerref-to-ignore-events-rewdh

<img width="264" alt="Screen Shot 2020-09-16 at 2 05 41 PM" src="https://user-images.githubusercontent.com/6036168/93381045-b73e1900-f825-11ea-86ba-e4ab2bf680c5.png">

**Comment by SamSamskies** [comment]
Hi @kjkurtz, the outline seems to be there on purpose and was previously not showing up before because of a bug in the CSS. See the following PR in the `mapbox-gl-geocoder` repo for more details https://github.com/mapbox/mapbox-gl-geocoder/pull/343.

Their current demo (https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/) doesn't show the dotted line cause it's using the CSS from `mapbox-gl-geocoder` v4.5.1. The change in the PR was released in v4.6.0.
